language: python

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports]
          packages:
            - g++-7
            - zlib1g-dev
            - libbz2-dev
            - libboost-dev
            - cmake
            - cmake-data
            - make
            - automake

      env:
        - MB_PYTHON_VERSION=3.6

env:
  global:
    - TWINE_USERNAME=abuelanin
      # Note: TWINE_PASSWORD is set in Travis settings

before_install:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - g++ --version
    - which g++ 
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
    - chmod +x miniconda3.sh
    - ./miniconda3.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

script:
  - conda create --yes -n test python=3.6
  - source activate test
  - whereis python
  - conda install --yes cmake make
  - conda install -c anaconda libstdcxx-ng -y
  - conda install --yes -c conda-forge swig=4.0.1
  - /home/travis/miniconda3/envs/test/bin/python -m pip install cibuildwheel
  - which python
  - export CIBW_BEFORE_BUILD='mkdir build && cd build && cmake .. && make && cd .. && bash build.sh'
  - export CIBW_BUILD='cp36-*'
  # - export CIBW_ENVIRONMENT='PATH="$HOME/rust/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      /home/travis/miniconda3/envs/test/bin/python -m install twine
      /home/travis/miniconda3/envs/test/bin/python -m twine upload wheelhouse/*.whl
    fi