# As written, this configuration will build your wheels on every
# commit, but will only push to PyPI on tagged commits.

language: python

jobs:
  include:
    # perform a linux build
    # - services: docker
    - os: linux
      # language: c++

env:
  global:
    - TWINE_USERNAME=abuelanin
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

before_install:
    - g++ --version
    - which g++ 
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
    - chmod +x miniconda3.sh
    - ./miniconda3.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - before_install

install:
  - python3 -m pip install cibuildwheel==1.5.2
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda create --yes -n test python=3.8
  - source activate test
  - conda install --yes cmake make
  - conda install -c anaconda gcc -y
  - conda install -c anaconda libstdcxx-ng -y
  - conda install --yes -c conda-forge swig=4.0.1
  - bash build.sh

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi