language: python

matrix:
  # This will launch a separate build for each Python version you add
  # Feel free to add extra environment variables as needed
  include:
    - python: 3.5
    - python: 3.6

before_install:
  # Install the latest version of Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt

install:
  # Create a new environment
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  # Activate it
  - source activate test
  # Install various dependencies
  - conda install --yes numpy=1.8 pytest pip

script:
  # Run any test suite you may have
  - which python
  - which pip
