language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - PIP=pip
        - PYTHON=python
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip
        - PYTHON=python
    - os: osx
      language: generic
      env:
        - PIP=pip3
        - PYTHON=python3

env:
  global:
    - TWINE_USERNAME=abuelanin
      # Note: TWINE_PASSWORD is set in Travis settings

before_install:
    - g++ --version
    - which g++ 
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
    - chmod +x miniconda3.sh
    - ./miniconda3.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

script:
  -  conda create --yes -n test python=3.8
  - source activate test
  - conda install --yes cmake make
  - python -m pip install cibuildwheel
  - export CIBW_BEFORE_BUILD='mkdir build && cd build && cmake .. && make && cd .. && bash build.sh'
  # - export CIBW_ENVIRONMENT='PATH="$HOME/rust/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      $PYTHON -m twine upload wheelhouse/*.whl
    fi