language: python

matrix:
  include:
    # Linux
    - os: linux
      sudo: required
      compiler: 
        - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - make
            - automake
      env:
        - MB_PYTHON_VERSION=3.6

env:
  global:
    - TWINE_USERNAME=abuelanin
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings


compiler:
  - clang
  - gcc

before_install:
  # Install the latest version of Miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda  # Update CONDA without command line prompt

install:
  # Create a new environment
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  # Activate it
  - source activate test
  # Install various dependencies
  - conda install --yes pip
  - conda install --yes cmake make
  - conda install -c anaconda libstdcxx-ng -y
  - conda install --yes -c conda-forge swig=4.0.1
  - pip install cibuildwheel==1.5.2

script:
  # Run any test suite you may have
  - which python
  - which pip
  - swig -version
  - which g++
  - bash build.sh
  - export CIBW_BEFORE_BUILD='mkdir build && cd build && cmake .. && make && cd ..'
  - export CIBW_BUILD='cp36-*'
  - python -m cibuildwheel --output-dir wheelhouse


after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
